language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install natsort coveralls
  - pip install future
  - pip install Cython
  - pip install h5py
  - pip install scipy
  - pip install theano
before_install:
  - sudo apt-get install libblas-dev liblapack-dev gfortran
  - sudo apt-get install python-scipy python-numpy
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
script:
  - nosetests --with-cov --cover-package nntoolkit --logging-level=INFO
after_success:
  - coveralls
