language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - sudo apt-get install libblas-dev liblapack-dev gfortran
  - sudo apt-get install python-scipy python-numpy
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
install:
  - pip install coveralls tox-travis
  - pip install natsort
  - pip install future
  - pip install Cython
  - pip install h5py
  - pip install scipy
  - pip install theano
  - pip install PyYAML
script:
  - tox
after_success:
  - coveralls
